# Generated by Django 5.1.15 on 2026-07-08 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaroodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(help_text='How many darood were recited.')),
                ('date', models.DateField(help_text='The day this count is for.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The person this darood count belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='darood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Darood entry',
                'verbose_name_plural': 'Darood entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='darood_daro_date_a0fccc_idx'), models.Index(fields=['user', 'date'], name='darood_daro_user_id_322775_idx')],
            },
        ),
    ]
