# Generated by Django 5.1.15 on 2026-07-08 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darood', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='daroodentry',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daroodentry',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daroodentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='daroodentry',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Who created this entry (the submitter or the manager).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='daroodentry',
            index=models.Index(fields=['status'], name='darood_daro_status_d61817_idx'),
        ),
        migrations.AddIndex(
            model_name='daroodentry',
            index=models.Index(fields=['manager', 'status'], name='darood_daro_manager_05b008_idx'),
        ),
    ]
