# Generated by Django 5.1.15 on 2026-07-24 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darood', '0002_daroodentry_manager_daroodentry_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('add', 'Added to reserve'), ('submit', 'Submitted from reserve')], max_length=10)),
                ('count', models.PositiveIntegerField(help_text='How many darood this movement is for.')),
                ('date', models.DateField(help_text='The day this reserve movement is for.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, help_text='The approved entry created when reserve darood was submitted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve_submission', to='darood.daroodentry')),
                ('manager', models.ForeignKey(help_text='The manager who owns this reserve.', on_delete=django.db.models.deletion.CASCADE, related_name='reserve_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserve transaction',
                'verbose_name_plural': 'Reserve transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['manager', 'kind'], name='darood_rese_manager_386097_idx'), models.Index(fields=['manager', '-created_at'], name='darood_rese_manager_cb34e0_idx')],
            },
        ),
    ]
