"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the insecure dev key when DJANGO_SECRET_KEY is not set.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-j=91b2@y_v2e8ec&$3)s3ai*trc8=b-cvs5$82ob=2#$(k@e_p',
)

def _env_bool(name, default='False'):
    return os.environ.get(name, default).lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=''):
    return [v.strip() for v in os.environ.get(name, default).split(',') if v.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', 'True')

# Comma-separated list, e.g. "darood.example.com,127.0.0.1". Defaults to "*".
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', '*')

# Origins trusted for unsafe (POST) requests. ALLOWED_HOSTS covers the Host
# header, but Django also checks the browser's Origin against this list for
# CSRF -- and that comparison includes the scheme and the port. So an app
# reached on a non-default port (nginx publishing :8085) needs an entry that
# spells the port out, even though the host itself is already allowed.
# Entries without a scheme are expanded to both http:// and https://.
def _as_origins(entry):
    if '://' in entry:
        return [entry]
    return [f'http://{entry}', f'https://{entry}']


CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
    'https://*.ngrok.app',
    'https://*.ngrok.io',
]
for _entry in _env_list('DJANGO_CSRF_TRUSTED_ORIGINS'):
    CSRF_TRUSTED_ORIGINS += [
        o for o in _as_origins(_entry) if o not in CSRF_TRUSTED_ORIGINS
    ]

# A reverse proxy that forwards to the container on port 8000 usually rewrites
# the Host header, hiding the port the browser actually used and breaking the
# CSRF origin check above. Turn these on when the proxy sends X-Forwarded-Host
# / X-Forwarded-Port, so request.get_host() reflects the public URL.
USE_X_FORWARDED_HOST = _env_bool('DJANGO_USE_X_FORWARDED_HOST')
USE_X_FORWARDED_PORT = _env_bool('DJANGO_USE_X_FORWARDED_PORT')

# HTTPS hardening. Enable once TLS is terminated in front of the app
# (DJANGO_SECURE_SSL=True). Off by default so the container also works over
# plain HTTP behind a proxy while you get things wired up.
if _env_bool('DJANGO_SECURE_SSL'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31_536_000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    # Local apps
    'accounts',
    'darood',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serve static files directly from the app process (no separate web server).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # CORS must come before CommonMiddleware so preflight requests are handled.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.pending_approvals',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # DJANGO_SQLITE_PATH lets the DB file live on a mounted volume in Docker.
        'NAME': os.environ.get('DJANGO_SQLITE_PATH', BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('ur', 'اردو'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Serve static files through WhiteNoise. Use the hashed, compressed manifest
# storage in production; in DEBUG keep the plain storage so local development
# works without running `collectstatic` first.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Project-specific configuration
# ---------------------------------------------------------------------------

# Use our custom user model that carries a `role` in addition to Django's
# built-in username / first_name / last_name / is_active fields.
AUTH_USER_MODEL = 'accounts.User'

# Where Django's auth machinery redirects.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # JWT for the mobile app; session kept so the browsable API / web still work.
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    # Per-endpoint throttling (applied only where a scope is set, e.g. auth).
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'register': '5/min',
    },
}

# --- JWT (mobile auth) ------------------------------------------------------
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    # Old refresh tokens are blacklisted after rotation and on logout.
    'BLACKLIST_AFTER_ROTATION': True,
}

# --- CORS -------------------------------------------------------------------
# Native apps don't enforce CORS, but Expo web / browsers do. Allow all in
# DEBUG; in production list the exact origins via DJANGO_CORS_ORIGINS.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = _env_list('DJANGO_CORS_ORIGINS')

# --- Logging ----------------------------------------------------------------
# Django's default console handler is muted when DEBUG=False, which hides the
# reason behind rejected requests (a CSRF 403 says only "verification failed").
# Send security warnings to stdout so `docker logs` explains them.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '[{levelname}] {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'stdout': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'loggers': {
        'django.security': {'handlers': ['stdout'], 'level': 'WARNING', 'propagate': False},
        'django.request': {'handlers': ['stdout'], 'level': 'WARNING', 'propagate': False},
    },
}

# Show Django messages with Bootstrap-friendly CSS classes.
from django.contrib.messages import constants as message_constants  # noqa: E402

MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}
